# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCQlBEzlGjmDBunRk_pXEzMvSiwLbjJb
"""



from app import app

if __name__ == "__main__":
    app.run()